### PR TITLE
Fix aggregation worker S3 access issue when writing status file.

### PR DESCRIPTION
**Pull request by ccmoloney**
Ran up stack from scratch (sandbox) + discovered it couldn't write to status file.

### CODE REVIEW

**Comment by akashisama** [comment]
Woops didn't catch this while it was open. The job doesn't need permission to delete,I think the permission problem here was that it needed s3:PutObjectAcl. Instead of giving it s3:* we could be careful and only give
```
-                  - s3:Get*
 -                  - s3:List*
 -                  - s3:Put*
```

**Comment by ccmoloney** [comment]
Too late.  It has god-like omnipotence now! Muahahaha!!!

**Comment by ccmoloney** [comment]
Ps: every other function has s3:*

**Comment by lwgordonimos** [comment]
This looks like one of the ones we tightened permissions on, but it didn't get picked up simply by the deployment alone.

We should definitely avoid wildcard permissions, but "Put*" is fine for anything that needs full access to the objects in the bucket.

**Comment by lwgordonimos** [comment]
> Ps: every other function has s3:*

Every other function *shouldn't* have s3:* ;)

**Comment by ccmoloney** [comment]
y u no tidy them? <insert one of angus' screensavers here>

**Pull request merged**
