### PR TITLE
Added lambda to push batch logs to sumologic

### PR DESCRIPTION
**Pull request by bhasin85**
# Testing Instructions

1. Use following value to bring up the stack
Parameter: _**sumologicLambdaCodeURL**_ 
Value:_https://github.com/aodn/aws-wps/raw/sumologic_logs/wps-common/src/main/resources/index.zip_
2. Modify cloudformation and remove condition  _**Condition: IsProdEnvironment**_ form all sumologic resources
3. Submit a job
4. Go to SumoLogic search with following filters

```sql
_collector=aws-batch-wps
```

You will be able to see the aws batch  and lambda job logs in sumologic

### CODE REVIEW

**Comment by bhasin85** [comment]
I have not added api gateway logs as it is not very useful at this point. #94

**Comment by anguss00** [comment]
Got some conflicts in here now after the last merge sorry @bhasin85!

**Comment by bhasin85** [comment]
I will fix it up @anguss00 ... No problem

**Comment by bhasin85** [comment]
Good to go @anguss00

**Pull request merged**
