### PR TITLE
Don't create IAM role for log creation

### PR DESCRIPTION
**Pull request by akashisama**
since this is an account global and we don't want different aws-wps stacks stepping on each others toes

part of fixing https://github.com/aodn/issues/issues/484

### CODE REVIEW

**Comment by gsatimos** [comment]
just wondering @akashisama, with the self-contained role being removed, how does the the template now specify that it should now use `AodnApiGateayWriteCloudWatchLogsRole` from https://github.com/aodn/cloud-deploy/pull/456 ?

**Comment by lwgordonimos** [comment]
I'm wondering too! It's clear that it needs to be an account level config though, so it will need to be configured in an core infrastructure stack somehow rather than individual app stacks. As far as I know from what I saw/chatted about with Alex yesterday, if this is a central config, it's something the individual stacks shouldn't need to worry about at all.

**Comment by akashisama** [comment]
I was thinking the best thing would be to set it manually in any account we want logs from. We could add it with a core infrastructure stack using [AWS::ApiGateway::Account](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-account.html) but it has some weird exceptions for brand new accounts:

> **Important**
> 
> If an API Gateway resource has never been created in your AWS account, you must add a dependency on another API Gateway resource, such as an AWS::ApiGateway::RestApi or AWS::ApiGateway::ApiKey resource.
> 
> If an API Gateway resource has been created in your AWS account, no dependency is required (even if the resource was deleted).

**Comment by lwgordonimos** [comment]
Would be great to avoid any manual steps if possible though!

If `AWS::ApiGateway::RestApi` resources are free, we could create a dummy one along with the `AWS::ApiGateway::Account`resource in coreinfrastructure in order to ensure it is created automatically, regardless of any application stack stuff.

**Comment by akashisama** [comment]
We could, but to me having a dummy api randomly lying around seems worse than a manual step...

**Comment by lwgordonimos** [comment]
It's not ideal, but definitely preferable manually remembering to hack unmanaged resources in every account we have. Managed is always better than unmanaged, even with the odd kludgy thing like dummy resources.

**Pull request merged**
