### PR TITLE
Remove custom name from ComputeEnvironment - it stops it being able t…

### PR DESCRIPTION
**Pull request by ccmoloney**
…o be updated if required. IE: update_stack operation fails.

### CODE REVIEW

**Comment by lwgordonimos** [comment]
@jonescc @anguss00 can you recall whether there was a specific reason the compute environment was given a custom name?

The general rule in CF is to let it autogenerate the name unless there is a very good reason not to, because it can remove some of the nice deployment logic around replacing resources when redeploying (as in this case), so was wondering if there was a reason?

**Comment by jonescc** [comment]
I believe ankit did it that way.  I like this better.

**Comment by anguss00** [comment]
Can't think of a reason, reckon it's GTG

**Comment by ccmoloney** [comment]
So....we merging this?  :)

**Comment by akashisama** [comment]
When first developing the template we tried to give resources names which would allow us to see which stack the resource was attached to.  The default names give no such information: "ComputeEnvironment-dfc963579e2fdee". But @ccmoloney is right, ComputeEnvironmentName has "Update requires: Replacement" so we need to keep the default name creation so we can do updates😞.

**Pull request merged**
