### PR TITLE
Add some integration tests for AWS WPS

### PR DESCRIPTION
**Pull request by jonescc**
Specify the APS WPS Stack to test by setting the WPS_ENDPOINT environment variable.

Then run mvn verify in the integration-testing directory

### CODE REVIEW

**Comment by akashisama** [comment]
Is this supposed to be runnable against a stack's endpoint or is there a way to run our WPS on local machines? Caz I'm getting "javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure" when I point it at a stack endpoint.

**Comment by jonescc** [comment]
For some reason I still have wps-common as a dependency - did you clean install on main project first before building integration-tests project?  The change includes removing shading on the wps-common jar which I think was including a problematic version of http client.

I don't think this needs to include wps-common as a dependency anymore (and better if it didn't) but would be good to confirm that this is the issue.

**Comment by jonescc** [comment]
Looks like I removed the wps-common dependency locally but hadn't pushed up the change.  Change has now been pushed up - please retest.

**Comment by jonescc** [comment]
@akashisama - fixed issue looking up schemas on the classpath on windows

**Comment by jonescc** [comment]
@akashisama - another to try

**Comment by jonescc** [comment]
Paths imports removed

**Pull request merged**
