### PR TITLE
remove cloudformation template and dev script and migrate to chef-pri…

### PR DESCRIPTION
**Pull request by anguss00**
…vate

### CODE REVIEW

**Comment by ccmoloney** [comment]
So: what is the workflow to run up dev stacks locally once we implement this change?

**Comment by anguss00** [comment]
@ccmoloney sorry, I meant to close this PR but thought we'd keep it up for discussion. We're not going to move the files atm due to the dev environment being broken by it

**Comment by lwgordonimos** [comment]
After we started scratching the surface of the implications of moving it, I was not in favour of changing this just yet until we have a clear picture of how to support both the Jenkins AND dev workflows. There's no point making it harder to develop before we can identify the final resting place of the files and cater to both scenarios, so better to leave it for now and work around it in the Jenkins job until then.

**Comment by ccmoloney** [comment]
The relative paths to the deployment artefacts for the AWS package operation will probably be the tricky thing.

**Comment by lwgordonimos** [comment]
Jenkins scenario
* start in a checkout of chef-private (or wherever template/script lives, dedicated cloudformation repo?)
* need to get properties files
* artifacts are copied in from other jobs as a prebuild step

Developer scenario
* start in a checkout of aws-wps
* need to ZIP artifacts into expected relative path?
* need to get hold of template/deploy script
* need to get properties files (or expect a dev to just have one with appropriate values)

The Jenkins scenario is trivial to manage in a consistent way with pre-build steps etc.

Really need a consistent way for developers to interact with the template (and possibly different versions of the template).

**Pull request closed without merging**
